[colors.bright]
black = "{color8}"
blue = "{color9}"
cyan = "{color10}"
green = "{color11}"
magenta = "{color12}"
red = "{color13}"
white = "{color14}"
yellow = "{color15}"

[colors.normal]
black = "{color0}"
blue = "{color1}"
cyan = "{color2}"
green = "{color3}"
magenta = "{color4}"
red = "{color5}"
white = "{color6}"
yellow = "{color7}"

[colors.primary]
background = "{background}"
foreground = "{foreground}"
